name: Build Artic

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.6.2'
        host: 'windows'
        target: 'desktop'

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2

    - name: Configure CMake
      run: cmake -B build -S . -DCMAKE_PREFIX_PATH="${{ env.QTDIR }}" -G "Visual Studio 17 2022"

    - name: Build
      run: cmake --build build --config Release --parallel 2

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Artic-Windows
        path: build/bin/Release/
